# Nom de l'application
spring.application.name=backend
# Serveur
server.port=8085
# Base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/demon_invasion
spring.datasource.username=di_user
spring.datasource.password=admin
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
# JWT
jwt.secret=8&kL$2pQ!v9Z#mX5^tN1*rB7@jW4(yE6)uH3_fG9+zS0[aC2]xD5{oP8}iK1|qV4<nM
# 24 heures
jwt.expiration=86400000
